language: python
python:
  - "3.7"

script: skip

deploy:
  provider: heroku
  skip_cleanup: true
  app: molecious-ml
  api_key:
    secure: jpKDGHrD8sjjFqvnzF5LQUdPZNyER0Um6qk5krkbsfmeh4hBmIgMfpl3+XwscjaLhMhTjwy08tXsVvL/BK/RgUqRT+9G6TwPe7zLERdlETABqGvf+offYb41RkQqqHixVvKSVAcbpEH4GTySCs6T+Ap8HX47ZPXaCH3uz1Y+2JOMfMGPtEZObW7DsU74pW3KQY9WY5T9tuc+NhnTXXXaKXpWl+T1IPFTbUJRr31faL+PHybPOA1XHeJnT1n5DzCQp0M6AGzG5c1SSuN6aDkp3/qHf0KYX6SURN266OCd6EBDCPWae14Ga5PbSdeAVuU7wIhsHI380rCnGJ6m9foGENvcmpw1ndj7cxGdYdJhCc5wHAN4ztaSzcvzeF8hsXizO71zW8LzClVjrX1Z7jVcvLWTJdybTjOn/+fiO7/h2Xpvwp4ZrEwcTzg99F17DmstpItcjQKD/6wyJ4B4iYdUauwQaqeOaxt3lJFzIODs2A7y4w7UlRDlhH0A49dBx2ovSUvdhXkUpCFwr2giEZvRvYaRswNY8+LsVujiy1SKBa+PnOPbbUHgBECtGZYrFG0qAb6RcqDsvkol5Kp7LgoHXFn8BWApNSZ5us0m4JfaD91Cd2r7xlr2IWLcdeBWIEbAyKoxEZDXgtRC3Z1LuavRQGBHfOJUOV47KqZwEkqsNuo=
